application: margothegame
version: 0
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /assets/js/.*
  script: js.php
  secure: always

- url: /assets/js/static
  static_dir: assets/js/static
  secure: always
  application_readable: true

- url: /assets/css
  static_dir: assets/css
  secure: always

- url: /assets/fonts
  static_dir: assets/fonts
  secure: always

- url: /assets/images.*
  script: images.php
  secure: always

- url: /auth
  script: login.php
  secure: always

- url: /dev\..*
  script: devtools.php
  secure: always

- url: /app.*
  script: meta.php
  secure: always

- url: /trivia.*
  script: trivia.php
  secure: always

- url: /browserconfig.xml
  script: meta.php
  secure: always

- url: /.*
  script: main.php
  secure: always

skip_files:
- ^(.*/)?.*\.psd$
