application: margothegame
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /assets
  static_dir: assets

- url: /template\.php
  script: template.php

- url: /.*
  script: template.php
