application: margothegame
version: 0
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /assets/js/.*
  script: js.php

- url: /assets/css
  static_dir: assets/css

- url: /assets/images
  static_dir: assets/images

- url: /assets/fonts
  static_dir: assets/fonts

- url: /.*
  script: main.php

skip_files:
- ^(.*/)?.*\.psd$
